import { Link } from "@tanstack/react-router";
import { ArrowRight, Clock, Quote, Star } from "lucide-react";
import aboutImage from "@/assets/about-team.jpg";
import emergencyImage from "@/assets/emergency-plumbing.jpg";
import anaheimImage from "@/assets/loc-anaheim.jpg";
import { PageHero, ServiceCard } from "@/components/blocks";
import { CallBtn, Eyebrow, FinalCTA, Section } from "@/components/site";
import { BUSINESS, fullAddress } from "@/data/business";
import { LOCATIONS } from "@/data/locations";
import { POSTS } from "@/data/blog";
import { SERVICES } from "@/data/services";

export function ServicesPage() { return <><PageHero eyebrow="Residential" title="Plumbing Services In Anaheim" sub="Accurate diagnosis, upfront prices and lasting repairs for every part of your plumbing system." image={emergencyImage} imageAlt="Emergency plumber repairing a pipe in Anaheim"><CallBtn /></PageHero><Section><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{SERVICES.map(service => <ServiceCard key={service.slug} service={service} />)}</div></Section><FinalCTA /></>; }

export function AreasPage() { return <><PageHero eyebrow="Based In West Anaheim" title="Plumbing Across Orange County" sub="Fast local service from technicians who understand the pipe materials, water pressure and housing patterns in your neighborhood." image={anaheimImage} imageAlt="Anaheim California neighborhood served by Visoso Plumbing"><CallBtn /></PageHero><Section><div className="grid gap-6 md:grid-cols-2">{LOCATIONS.map(location => <Link key={location.slug} to="/$slug" params={{ slug: `plumber-${location.slug}-ca` }} className="group grid overflow-hidden rounded-3xl border border-border bg-card shadow-card sm:grid-cols-[12rem_1fr]"><img src={location.image} alt={location.imageAlt} loading="lazy" className="h-full min-h-52 w-full object-cover" /><div className="p-6"><p className="text-xs font-bold uppercase text-accent">ZIP {location.zips.join(", ")}</p><h2 className="mt-2 text-2xl font-bold">Plumber in {location.name}</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{location.intro.join(" ")}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary">View Plumber in {location.name} <ArrowRight className="h-4 w-4" /></span></div></Link>)}</div></Section><FinalCTA title="Need A Local Plumber Today?" /></>; }

export function AboutPage() { return <><PageHero eyebrow="Visoso Plomería Económica" title="Local Plumbing With Standards" sub="Visoso Plumbing is a free service that connects homeowners with local plumbing service providers in Anaheim and Orange County." image={aboutImage} imageAlt="Visoso Plumbing service"><CallBtn /></PageHero><Section><div className="mx-auto max-w-4xl prose-local"><h2>Connecting Anaheim Homeowners with Local Pros</h2><p>Visoso Plumbing serves homeowners by connecting them with local service providers. Local professionals understand the plumbing patterns of the neighborhoods they serve and carry the parts those homes actually need.</p><p>Many providers work in English and Spanish, answer emergencies around the clock and provide a clear price before approved work begins.</p><h2>What you can expect</h2><ul>{["A realistic arrival window", "Protection for floors and finished surfaces", "Diagnosis before replacement", "Repair options explained in plain language", "Testing after work is complete", "A clean workspace and workmanship warranty"].map(i=><li key={i}>{i}</li>)}</ul><h2>Residential plumbing connection service</h2><p>Providers work on residential homes and properties. Fully stocked vehicles let them finish most routine repairs in one visit.</p></div></Section><FinalCTA /></>; }

export function ContactPage() { return <><Section className="surface-ink"><div className="grid gap-12 lg:grid-cols-2"><div><Eyebrow>Open 24 Hours</Eyebrow><h1 className="mt-5 text-4xl font-extrabold md:text-6xl">Connect With A Local Plumber</h1><p className="mt-5 max-w-xl text-lg opacity-80">For fastest service, call now for an estimate and provide your name, service address and details of the problem.</p><div className="mt-8 flex flex-wrap gap-3"><CallBtn label={`Call ${BUSINESS.phoneDisplay}`} /></div></div><div className="glass-panel rounded-3xl p-7"><dl className="grid gap-6"><div><dt className="text-xs font-bold uppercase opacity-60">Phone</dt><dd className="mt-1 text-xl font-bold">{BUSINESS.phoneDisplay}</dd></div><div><dt className="text-xs font-bold uppercase opacity-60">Address</dt><dd className="mt-1 font-semibold">{fullAddress}</dd></div><div><dt className="text-xs font-bold uppercase opacity-60">Hours</dt><dd className="mt-1 font-semibold">{BUSINESS.hours}</dd></div><div><dt className="text-xs font-bold uppercase opacity-60">Languages</dt><dd className="mt-1 font-semibold">English & Español</dd></div></dl></div></div></Section><Section><div className="overflow-hidden rounded-3xl border border-border shadow-card"><iframe title="Visoso Plumbing location map" src={BUSINESS.mapEmbed} className="h-[32rem] w-full" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div></Section><FinalCTA /></>; }

export function BlogPage() { return <><Section className="surface-ink text-center"><Eyebrow>Plumbing Advice</Eyebrow><h1 className="mt-5 text-4xl font-extrabold md:text-6xl">The Visoso Plumbing Guide</h1><p className="mx-auto mt-4 max-w-2xl opacity-80">Practical, local guidance for preventing damage, understanding repairs and making better plumbing decisions.</p></Section><Section><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{POSTS.map(post=><Link key={post.slug} to="/blog/$postSlug" params={{postSlug:post.slug}} className="flex flex-col rounded-2xl border border-border bg-card p-6 shadow-card transition-transform hover:-translate-y-1"><div className="flex items-center justify-between text-xs font-bold uppercase text-accent"><span>{post.category}</span><span className="flex items-center gap-1 text-muted-foreground"><Clock className="h-3.5 w-3.5"/>{post.readMinutes} min</span></div><h2 className="mt-4 text-xl font-bold">{post.title}</h2><p className="mt-3 flex-1 text-sm leading-relaxed text-muted-foreground">{post.excerpt}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary">Read guide <ArrowRight className="h-4 w-4"/></span></Link>)}</div></Section><FinalCTA /></>; }

export function LegalPage({ title, kind }: { title: string; kind: "privacy" | "terms" }) { return <Section><div className="mx-auto max-w-3xl prose-local"><Eyebrow>Visoso Plumbing</Eyebrow><h1 className="mt-5 text-4xl font-extrabold">{title}</h1><p>Last updated August 4, 2026.</p>{kind === "privacy" ? <><h2>Information we receive</h2><p>When you call, email or message us, we may receive your name, contact details, service address, photos and information about the service requested.</p><h2>How information is used</h2><p>We do not sell personal information. All contractors/providers are independent and Visoso Plumbing does not warrant or guarantee any work performed. It is the responsibility of the homeowner to verify that the hired contractor furnishes the necessary license and insurance required for the work being performed. Details may be shared only with providers needed to complete your requested work or comply with law.</p><h2>Your choices</h2><p>You may ask us to correct or delete contact information by calling {BUSINESS.phoneDisplay}.</p></> : <><h2>Service estimates</h2><p>Estimates are based on conditions visible during diagnosis. Approved changes in scope are explained and priced before additional work begins.</p><h2>Appointments and emergencies</h2><p>Arrival windows are estimates affected by traffic and active emergency calls. Providers communicate material delays.</p><h2>Workmanship</h2><p>Warranty terms depend on the service and materials selected and will be described on the service invoice.</p></>}</div></Section>; }